# Decision Tree Classifier

In this notebook, you will implement your own decision tree algorithm for the classification problem. You are supposed to learn:

* How to prepare the dataset for training and testing of the model (i.e. decision tree).
* How to implement the decision tree learning algorithm.
* How to classify unseen samples using your model (i.e. trained decision tree).
* How to evaluate the performance of your model.

**Instructions:**

* Read carefuly through this notebook. Be sure you understand what is provided to you, and what is required from you.
* Place your code/edit only in sections annotated with `### START CODE HERE ###` and `### END CODE HERE ###`.
* Use comments whenever the code is not self-explanatory.
* Submit an executable notebook (`*.ipynb`) with your solution to BlackBoard.

Enjoy :-)

## Packages

Following packages is all you need. Do not import any additional packages!

* [Pandas](https://pandas.pydata.org/) is a library providing easy-to-use data structures and data analysis tools.
* [Numpy](http://www.numpy.org/) library provides support for large multi-dimensional arrays and matrices, along with functions to operate on these.

In [841]:
import pandas as pd
import numpy as np


## Problem

You are given a dataset `mushrooms.csv` with characteristics/attributes of mushrooms, and your task is to implement, train and evaluate a decision tree classifier able to say whether a mushroom is poisonous or edible based on its attributes.

## Dataset

The dataset of mushroom characteristics is freely available at [Kaggle Datasets](https://www.kaggle.com/uciml/mushroom-classification) where you can find further information about the dataset. It consists of 8124 mushrooms characterized by 23 attributes (including the class). Following is the overview of attributes and values:

* class: edible=e, poisonous=p
* cap-shape: bell=b,conical=c,convex=x,flat=f, knobbed=k,sunken=s
* cap-surface: fibrous=f,grooves=g,scaly=y,smooth=s
* cap-color: brown=n,buff=b,cinnamon=c,gray=g,green=r,pink=p,purple=u,red=e,white=w,yellow=y
* bruises: bruises=t,no=f
* odor: almond=a,anise=l,creosote=c,fishy=y,foul=f,musty=m,none=n,pungent=p,spicy=s
* gill-attachment: attached=a,descending=d,free=f,notched=n
* gill-spacing: close=c,crowded=w,distant=d
* gill-size: broad=b,narrow=n
* gill-color: black=k,brown=n,buff=b,chocolate=h,gray=g, green=r,orange=o,pink=p,purple=u,red=e,white=w,yellow=y
* stalk-shape: enlarging=e,tapering=t
* stalk-root: bulbous=b,club=c,cup=u,equal=e,rhizomorphs=z,rooted=r,missing=?
* stalk-surface-above-ring: fibrous=f,scaly=y,silky=k,smooth=s
* stalk-surface-below-ring: fibrous=f,scaly=y,silky=k,smooth=s
* stalk-color-above-ring: brown=n,buff=b,cinnamon=c,gray=g,orange=o,pink=p,red=e,white=w,yellow=y
* stalk-color-below-ring: brown=n,buff=b,cinnamon=c,gray=g,orange=o,pink=p,red=e,white=w,yellow=y
* veil-type: partial=p,universal=u
* veil-color: brown=n,orange=o,white=w,yellow=y
* ring-number: none=n,one=o,two=t
* ring-type: cobwebby=c,evanescent=e,flaring=f,large=l,none=n,pendant=p,sheathing=s,zone=z
* spore-print-color: black=k,brown=n,buff=b,chocolate=h,green=r,orange=o,purple=u,white=w,yellow=y
* population: abundant=a,clustered=c,numerous=n,scattered=s,several=v,solitary=y
* habitat: grasses=g,leaves=l,meadows=m,paths=p,urban=u,waste=w,woods=d

Let's load the dataset into so called Pandas dataframe.

In [842]:
mushrooms_df = pd.read_csv('mushrooms.csv')

Now we can take a closer look at the data.

In [843]:
mushrooms_df

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

You can also print an overview of all attributes with the counts of unique values.

In [844]:
mushrooms_df.describe().T


count unique top  freq
class                     8124      2   e  4208
cap-shape                 8124      6   x  3656
cap-surface               8124      4   y  3244
cap-color                 8124     10   n  2284
bruises                   8124      2   f  4748
odor                      8124      9   n  3528
gill-attachment           8124      2   f  7914
gill-spacing              8124      2   c  6812
gill-size                 8124      2   b  5612
gill-color                8124     12   b  1728
stalk-shape               8124      2   t  4608
stalk-root                8124      5   b  3776
stalk-surface-above-ring  8124      4   s  5176
stalk-surface-below-ring  8124      4   s  4936
stalk-color-above-ring    8124      9   w  4464
stalk-color-below-ring    8124      9   w  4384
veil-type                 8124      1   p  8124
veil-color                8124      4   w  7924
ring-number               8124      3   o  7488
ring-type                 8124      5   p  3968
spore-print-color         8124      9   w  2388
population                8124      6   v  4040
habitat                   8124      7   d  3148

The dataset is pretty much balanced. That's a good news for the evaluation.

## Dataset Preprocessing

As our dataset consist of nominal/categorical values only, we will encode the strings into integers which again should simplify our implementation.

In [845]:
def encode_labels(df):
    import sklearn.preprocessing
    encoder = {}
    for col in df.columns:
        le = sklearn.preprocessing.LabelEncoder()
        le.fit(df[col])
        df[col] = le.transform(df[col])
        encoder[col] = le
    return df, encoder    

mushrooms_encoded_df, encoder = encode_labels(mushrooms_df)

In [846]:
mushrooms_encoded_df

class  cap-shape  cap-surface  cap-color  bruises  odor  \
0         1          5            2          4        1     6   
1         0          5            2          9        1     0   
2         0          0            2          8        1     3   
3         1          5            3          8        1     6   
4         0          5            2          3        0     5   
...     ...        ...          ...        ...      ...   ...   
8119      0          3            2          4        0     5   
8120      0          5            2          4        0     5   
8121      0          2            2          4        0     5   
8122      1          3            3          4        0     8   
8123      0          5            2          4        0     5   

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
0                   1             0          1           4  ...   
1                   1             0          0           4  ...   
2                   1             0          0           5  ...   
3                   1             0          1           5  ...   
4                   1             1          0           4  ...   
...               ...           ...        ...         ...  ...   
8119                0             0          0          11  ...   
8120                0             0          0          11  ...   
8121                0             0          0           5  ...   
8122                1             0          1           0  ...   
8123                0             0          0          11  ...   

      stalk-surface-below-ring  stalk-color-above-ring  \
0                            2                       7   
1                            2                       7   
2                            2                       7   
3                            2                       7   
4                            2                       7   
...                        ...                     ...   
8119                         2                       5   
8120                         2                       5   
8121                         2                       5   
8122                         1                       7   
8123                         2                       5   

      stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
0                          7          0           2            1          4   
1                          7          0           2            1          4   
2                          7          0           2            1          4   
3                          7          0           2            1          4   
4                          7          0           2            1          0   
...                      ...        ...         ...          ...        ...   
8119                       5          0           1            1          4   
8120                       5          0           0            1          4   
8121                       5          0           1            1          4   
8122                       7          0           2            1          0   
8123                       5          0           1            1          4   

      spore-print-color  population  habitat  
0                     2           3        5  
1                     3           2        1  
2                     3           2        3  
3                     2           3        5  
4                     3           0        1  
...                 ...         ...      ...  
8119                  0           1        2  
8120                  0           4        2  
8121                  0           1        2  
8122                  7           4        2  
8123                  4           1        2  

[8124 rows x 23 columns]

## Dataset Splitting

Before we start with the implementation of our decision tree algorithm we need to prepare our dataset for the training and testing.

First, we divide the dataset into attributes (often called features) and classes (often called targets). Keeping attributes and classes separately is a common practice in many implementations. This should simplify the implementation and make the code understandable.

In [847]:
X_df = mushrooms_encoded_df.drop('class', axis=1)  # attributes
y_df = mushrooms_encoded_df['class']  # classes
X_array = X_df.as_matrix()
y_array = y_df.as_matrix()

/opt/anaconda2/envs/py3/lib/python3.5/site-packages/ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until
/opt/anaconda2/envs/py3/lib/python3.5/site-packages/ipykernel_launcher.py:4: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  after removing the cwd from sys.path.


And this is how it looks like.

In [848]:
print('X =', X_array)
print('y =', y_array)

## X are the coloums and rows of the mushrooms aka a matrix
#Y is a array (coloumn) that sais if the mushrom is poisonous or not

X = [[5 2 4 ... 2 3 5]
 [5 2 9 ... 3 2 1]
 [0 2 8 ... 3 2 3]
 ...
 [2 2 4 ... 0 1 2]
 [3 3 4 ... 7 4 2]
 [5 2 4 ... 4 1 2]]
y = [1 0 0 ... 0 1 0]


Next, we need to split the attributes and classes into training sets and test sets.

**Exercise:**

Implement the holdout splitting method with shuffling.

In [849]:
def train_test_split(X, y, test_size=0.2):
    from random import randint
    
   
    ### START CODE HERE ###
    #training set is largest, y set is 8124 rows.
    
    #set size of testSet
    testSize= round(test_size*len(y))+1
    
    #merge X and y into one list
    data= zip(X,y)
    tempTestList=list()
    
    tempTrainList= list(data)
    for i in range(testSize-1):
        #shuffle the data by selecting random elements
        
        item=randint(0,len(tempTrainList)-i)
        ##remove items from data and add to test list
        tempTestList.append(tempTrainList.pop(item))
    
        
    X_train, y_train= zip(*tempTrainList)
    X_test, y_test=zip(*tempTestList)
    
    ### END CODE HERE ###
    ##nicer display of arrays
    return np.array(X_train), np.array(X_test), np.array(y_train), np.array(y_test)
   

Let's split the dataset into training and validation/test set with 67:33 split.

In [850]:
X_train, X_test, y_train, y_test = train_test_split(X_array, y_array, 0.33)

In [851]:
print('X_train =', X_train)
print('y_train =', y_train)
print('X_test =', X_test)
print('y_test =', y_test)


X_train = [[5 2 4 ... 2 3 5]
 [5 2 9 ... 3 2 1]
 [5 3 9 ... 2 2 1]
 ...
 [2 2 4 ... 0 1 2]
 [3 3 4 ... 7 4 2]
 [5 2 4 ... 4 1 2]]
y_train = [1 0 0 ... 0 1 0]
X_test = [[2 3 4 ... 3 3 5]
 [5 2 5 ... 2 4 0]
 [5 2 2 ... 7 4 4]
 ...
 [5 3 4 ... 2 5 1]
 [5 0 3 ... 2 4 0]
 [2 0 9 ... 1 5 1]]
y_test = [1 1 1 ... 0 0 1]


A quick sanity check...

In [852]:
assert len(X_train) == len(y_train)
assert len(y_train) == 5443
assert len(X_test) == len(y_test)
assert len(y_test) == 2681
print(len(X_test))

      

2681


## Training

**Exercise:**

Implement an algorithm for fitting (also called training or inducing) a decision tree.

* You have a free hand regarding the generation of candidate splits (also called attribute test conditions).
* Measure the degree of impurity (Gini) to select the best split.

   

In [927]:
# Use this section to place any "helper" code for the `fit()` function.

### START CODE HERE ###
from __future__ import print_function


#get the unique values for each feature/attribute. Need to specify new col for each iteration
def uniqueValue(X, col):
    return set((row[col] for row in X))


#counts the number of poisionous and unpoisionous mushrooms aka counts # of 0 and 1
def classCounts(y, col =None):
    counts = {}  
    for val in y:
        label=val
        if col:
            label= label[col]
        if label not in counts:
            counts[label] = 0
            
        counts[label] += 1
    return counts
        



##asks if value of attribute is equal to a spesific value
class Question:
   
    def __init__(self, column, value):
        self.column = column
        self.value = value

    def match(self, example):
        val = example[self.column]
        
        ##returns true if example matches question
        return val == self.value
        

             
#asks question to see which branch(list) to put the mushroom (row in attributes) in
def partition(X, question, y):
    trueRows_y,falseRows_y=[],[]
    trueRows_X,falseRows_X=[],[]
    for i in range(len(X)):
        
        if question.match(X[i]):
            trueRows_X.append(X[i])  #get the rows in X that are true
            trueRows_y.append(y[i])  #get the corresponding class label 
        else:
            falseRows_X.append(X[i])
            falseRows_y.append(y[i])

    return trueRows_y, falseRows_y, trueRows_X, falseRows_X




##Choose the Gini Impurity for rows in order to find best split
#gini impurity for a list of rows using the class label y
def gini(y):
    
    #get number of poisinous and unposionous mushrooms, thus only takes y
    counts = classCounts(y)
    giniVal = 1
    #p refers to the fraction of records that belong to one of the two classe 
    for i in counts:
        prob = counts[i] / float(len(y))
        giniVal -= prob**2
    return giniVal

#get the information gain for next potential split
#measure of goodnes of split
#left is true and right is false split
def infoGain(left, right, currentGini):
    
    p = float(len(left)) / (len(left) + len(right))
    giniLeft= p * gini(left)
    giniRight=(1-p)*gini(right)
    gain = currentGini-giniLeft-giniRight
    return gain

    
def findBestSplit(X,y):
    bestQuestion = None  
    bestGain = 0  
    features = len(X[0]) - 1  
    currentGini = gini(y)

    #for every feature(cap-surface smell etc) iterate over every value(0,2,1 etc) and partition(ask question) 
    for col in range(features):  
        
        #find the unique values in the coloms of X
        values = set([row[col] for row in X])
        
        for val in values:  
            
            question = Question(col, val)
            trueRows, falseRows, trueRowsX,falseRowsy = partition(X, question, y)

            # only split if it devides dataset
            if len(trueRows) == 0 or len(falseRows) == 0:
                continue

            gain = infoGain(trueRows, falseRows, currentGini)

            if gain >= bestGain:
                bestGain, bestQuestion= gain, question
                
    return bestGain, bestQuestion




class Leaf:
    

    def __init__(self, y):
        self.predictions = classCounts(y)
        
class DecisionNode:
    

    def __init__(self,
                 question,
                 trueBranch,
                 falseBranch):
        self.question = question
        self.trueBranch = trueBranch
        self.falseBranch = falseBranch
        






### END CODE HERE ###

In [928]:
def fit(X, y):
   
    ### START CODE HERE ### 
    
    ##Build trees
    #returns the question that produces the highest gain.
    gain, question = findBestSplit(X,y)

    #no further info gain, dont need to ask more questions
    if gain == 0:
        return Leaf(y)

    #can partition on useful feature
    trueRowsY, falseRowsY, trueRowsX, falseRowsX = partition(X, question, y)

    trueBranch = fit(trueRowsX, trueRowsY)

    falseBranch = fit(falseRowsX, falseRowsY)

    # Returns a question node with the best feature to ask 
    classifier= DecisionNode(question, trueBranch, falseBranch)
    

 ### END CODE HERE ### 
    return classifier


In [929]:
model = fit(X_train, y_train)


## Prediction/Deduction

At this moment we should have trained a decision tree (our model). Now we need an algorithm for assigning a class given the attributes and our model.

**Exercise:**

Implement an algorithm deducing class given the attributes and the model.

* `X` is a matrix of attributes of one or more instances for classification.

In [930]:
# Use this section to place any "helper" code for the `predict()` function.

### START CODE HERE ###

def classify(X,node):
    #  reached a leaf
    if isinstance(node, Leaf):
        return node.predictions
        
   #decide if we are going to follow true or false branch
    #determinesthe classlabel to be assignedto a leaf node.
    if node.question.match(X):
        trueBranch =classify(X, node.trueBranch)
        return trueBranch
        
    else:
        falseBranch=classify(X, node.falseBranch)
        return falseBranch
    
def print_nice(counts):
    total = sum(counts.values()) * 1.0
    probs = {}
    for lbl in counts.keys():
        probs[lbl] = int(counts[lbl] / total )
    return probs

#method for comparing the prediction array to values in actual class array
#just for testing
testList=[]
def test(y_test):
    for i in range(10):
        testList.append(y_test[i])
    return testList

print(test(y_test))

y_hat = []

### END CODE HERE ###

In [935]:
def predict(X, my_tree):
### START CODE HERE ###
 
    for row in X_test:
        #print (print_leaf(classify(testing_data_X, my_tree)))
        predict= classify(row,model)
        for key in predict:
            y_hat.append(key)
                      

### END CODE HERE ###
    return y_hat

Let's classify the instances of our test set.

In [936]:
y_hat = predict(X_test, model)


First ten predictions of the test set.

In [937]:
y_hat[:10]

[1, 1, 1, 0, 1, 1, 0, 0, 1, 1]

## Evaluation

Now we would like to assess how well our decision tree classifier performs.

**Exercise:**

Implement a function for calculating the accuracy of your predictions given the ground truth and predictions.

In [938]:
def evaluate(y_true, y_pred):
  
    ### START CODE HERE ###
    correctPredict = 0
    falsePredict = 0
    totalPredict = len(y_pred)
    
    for i in range(totalPredict):
        if(y_true[i]==y_pred[i]):
            correctPredict += 1
        else:
            falsePredict += 1
    
    accuracy = correctPredict/totalPredict
    ### END CODE HERE ### 
    return accuracy

In [939]:
accuracy = evaluate(y_test, y_hat)
print('accuracy =', accuracy)

accuracy = 1.0


How many items where misclassified?

In [940]:
print('misclassified =', sum(abs(y_hat - y_test)))

misclassified = 0


How balanced is our test set?

In [926]:
np.bincount(y_test)

array([1540, 1141])

If it's balanced, we don't have to be worried about objectivity of the accuracy metric.

---

Congratulations! At this point, hopefully, you have successufuly implemented a decision tree algorithm able to classify unseen samples with high accuracy.

✌️